version: '3'

networks:
  net:
    driver: host

services:
  flask:
    build:
      context: .
      dockerfile: flask.dockerfile
    networks:
      - net
    volumes:
      - ../flask-mnt:/akai-code:rw
    working_dir: akai-code
    tty: true
    stdin_open: true
    ports:
      - 5000:5000
    entrypoint: 'python3 -m flask run -p 5000'
  # postgres:
  #   image: postgres
  #   networks:
  #     - net
  #   volumes:
  #     - '../docker/psql:/entrypoints:rw'
  #   entrypoint: '/bin/bash /entrypoints/entrypoint.sh'
  # model:
  #   build:
  #     context: .
  #     dockerfile: model.dockerfile
  #   networks:
  #     - net

